name: "Render Helm Chart" 
description: "Runs basic Helm template render" 
inputs: 
  template_path: 
    description: 'path to template' 
    required: true 
  report_full_template: 
    description: 'Indicated if the full template should be posted to github comment. Consider switchit it off for massive charts' 
    default: true 
    required: false 
  lint_args: 
    description: 'Adds additional arguments to "helm lint" command' 
    required: false 
  template_args: 
    description: 'Adds additional arguments to "helm template" command' 
    required: false 
runs: 
  using: "composite" 
  steps: 
    - name: Render template 
      id: template 
      run: | 
        helm template testing ${{ inputs.template_path }} ${{ inputs.template_args }} 2>&1 | tee content.yaml 
      shell: bash
 
    - name: Report Template result 
      uses: actions/github-script@v6 
      with: 
        script: |
          const fs = require('fs');
          const content = fs.readFileSync('content.yaml', 'utf8');
       
          github.rest.issues.createComment ({
            owner: context.repo.owner, 
            repo: context.repo.repo,
            issue_numer: context.issue.number,
            body: 'Rendered Helm chart:\n```yaml\n' + content + '\n```'
          });
